# Generated by Django 3.2.13 on 2022-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='FAQ Question')),
                ('answer', models.TextField(verbose_name='FAQ Answer')),
            ],
        ),
    ]
