module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './node_modules/tw-elements/dist/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        'carbon-path-blue': '#1C3568',
        'carbon-path-green': '#69DAB9',
        'carbon-path-bluegrey': '#385877',
        'carbon-path-lightblue': '#6AEAEA',
        'carbon-path-cyan': '#05DEC9',
        'carbon-path-bluestroke': '#182B51',
        'carbon-path-gray': '#515151',
        'carbon-path-graytext': '#9EA1AE',
        'carbon-path-lightgray': '#ECEFFA',
        gray: {
          light: '#8A8A8A',
          middle: '#606060',
          normal: '#333333',
        },
      },
      backgroundImage: {
        'hero-bg': "url('../public/images/hero-bg.png')",
        'hero-bg-temp': "url('../public/images/hero-bg-temp.png')",
        'hero-bg-mobile': "url('../public/images/hero-bg-mobile.png')",
        'landing-pic-2': "url('../public/images/landing-pic-2.png')",
        'landing-pic-2-mobile': "url('../public/images/landing-pic-2-mobile.png')",
        'landing-pic-3': "url('../public/images/landing-pic-3.png')",
        'landing-pic-4': "url('../public/images/landing-pic-4.png')",
        'landing-pic-4-mobile': "url('../public/images/landing-pic-4-mobile.png')",
        'carousel-bg-1': "url('../public/images/carousel-bg-1.png')",
        'impact-1': "url('../public/images/impact-1.png')",
        'impact-2': "url('../public/images/impact-2.png')",
        'impact-2-rect': "url('../public/images/impact-2-rect.png')",
        'impact-3': "url('../public/images/impact-3.png')",
        'impact-3-rect': "url('../public/images/impact-3-rect.png')",
        'impact-1-mobile': "url('../public/images/impact-1-mobile.png')",
        'impact-2-mobile': "url('../public/images/impact-2-mobile.png')",
        'impact-3-mobile': "url('../public/images/impact-3-mobile.png')",
        'companies-bg': "url('../public/images/companies-bg.png')",
        'allies-bg': "url('../public/images/allies-bg.png')",
        'partners-bg': "url('../public/images/partners-bg.png')",
        'individuals-bg': "url('../public/images/individuals-bg.png')",
        'satellite-map-icon': "url('../public/images/satellite-map-icon.png')",
        'base-map-icon': "url('../public/images/base-map-icon.png')",
      },
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      screens: {
        '3xl': '1792px',
        '4xl': '1920px',
        '5xl': '2560px',
      },
    },
  },
  plugins: [require('tw-elements/dist/plugin')],
}
