# Generated by Django 3.2.15 on 2022-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Map Plan ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Map Plan Name')),
                ('geometry', models.JSONField()),
            ],
            options={
                'verbose_name': 'Map Plan',
                'verbose_name_plural': 'Map Plans',
            },
        ),
        migrations.CreateModel(
            name='PanoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Pano Plan ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Pano Plan Name')),
                ('geometry', models.JSONField()),
                ('download_path', models.URLField()),
            ],
            options={
                'verbose_name': 'Pano Plan',
                'verbose_name_plural': 'Pano Plans',
            },
        ),
        migrations.CreateModel(
            name='PhotoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Photo Plan ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Photo Plan Name')),
                ('geometry', models.JSONField()),
                ('download_path', models.URLField()),
            ],
            options={
                'verbose_name': 'Photo Plan',
                'verbose_name_plural': 'Photo Plans',
            },
        ),
        migrations.CreateModel(
            name='VideoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Video Plan ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Video Plan Name')),
                ('geometry', models.JSONField()),
                ('download_path', models.URLField()),
            ],
            options={
                'verbose_name': 'Video Plan',
                'verbose_name_plural': 'Video Plans',
            },
        ),
    ]
