# Generated by Django 3.2.15 on 2022-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedeploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplan',
            name='bounds',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mapplan',
            name='download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mapplan',
            name='file',
            field=models.FileField(null=True, upload_to='dronedeploy/map_plans'),
        ),
        migrations.AlterField(
            model_name='mapplan',
            name='geometry',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='panoplan',
            name='download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='panoplan',
            name='geometry',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='photoplan',
            name='download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='photoplan',
            name='geometry',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='videoplan',
            name='download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videoplan',
            name='geometry',
            field=models.JSONField(null=True),
        ),
    ]
