# Generated by Django 3.2.15 on 2022-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedeploy', '0003_auto_20220928_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapplan',
            name='bounds',
        ),
        migrations.RemoveField(
            model_name='mapplan',
            name='download_path',
        ),
        migrations.AddField(
            model_name='mapplan',
            name='geotiff_bounds',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mapplan',
            name='geotiff_download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mapplan',
            name='jpeg_bounds',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='mapplan',
            name='jpeg_download_path',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
