# Generated by Django 3.2.15 on 2022-09-30 05:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dronedeploy', '0005_alter_mapplan_jpeg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplan',
            name='jpeg_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[4096, None], upload_to='dronedeploy/map_plans_jpeg'),
        ),
    ]
