# Generated by Django 3.2.15 on 2022-10-11 20:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronedeploy', '0006_alter_mapplan_jpeg_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoplan',
            name='download_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000, null=True), null=True, size=None),
        ),
    ]
