# Generated by Django 3.2.14 on 2022-09-01 01:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(default=users.models.generate_nonce, editable=False, max_length=100, verbose_name='Nonce'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Wallet Address'),
        ),
    ]
