# Generated by Django 3.2.15 on 2022-09-16 01:22

from django.db import migrations


class Migration(migrations.Migration):
    def forward_func(apps, schema_editor):
        to_add = []

        User = apps.get_model("users", "User")
        for user in User.objects.all():
            if user.wallet_address:
                user.username = user.wallet_address
            elif user.email:
                user.username = user.email

            user.save()

    def backward_func(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            user.username = ""

            user.save()

    dependencies = [
        ("users", "0004_auto_20220916_0120"),
    ]
    operations = [migrations.RunPython(forward_func, backward_func)]
