# Generated by Django 3.2.13 on 2022-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Well Name')),
                ('cost_per_tonne', models.IntegerField(max_length=12, verbose_name='Cost Per Tonne in USD')),
                ('tonnes', models.IntegerField(max_length=12, verbose_name='Tonnes Count')),
                ('status', models.CharField(max_length=64, verbose_name='Status')),
                ('type', models.CharField(max_length=32, verbose_name='Type')),
                ('source', models.CharField(max_length=32, verbose_name='Source')),
                ('contract_address', models.CharField(max_length=64, verbose_name='Contract Address')),
                ('token_id', models.CharField(max_length=64, verbose_name='Token ID')),
                ('blockchain', models.CharField(max_length=64, verbose_name='Blockchain')),
                ('metadata', models.CharField(max_length=64, verbose_name='Metadata')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile-pictures/', verbose_name='Profile Picture')),
                ('field', models.CharField(max_length=64, verbose_name='Field')),
                ('county', models.CharField(max_length=64, verbose_name='County')),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District Of Columbia', 'District Of Columbia'), ('Federated States Of Micronesia', 'Federated States Of Micronesia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Marshall Islands', 'Marshall Islands'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Palau', 'Palau'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=64, verbose_name='State')),
                ('md', models.IntegerField(max_length=12, verbose_name='Measured Depth in ft')),
                ('tvd', models.IntegerField(max_length=12, verbose_name='True Vertical Depth in ft')),
                ('producing_formation', models.CharField(max_length=64, verbose_name='Producing Formation')),
                ('legal_description', models.CharField(max_length=64, verbose_name='legal_description')),
                ('lease_id', models.IntegerField(max_length=12, verbose_name='Lease ID/Unit ID/Production ID')),
                ('well_type', models.CharField(max_length=64, verbose_name='Well Type')),
                ('township', models.CharField(max_length=8, verbose_name='Township')),
                ('range', models.CharField(max_length=8, verbose_name='Range')),
                ('shl_section', models.IntegerField(max_length=12, verbose_name='SHL Section')),
                ('bhl_section', models.IntegerField(max_length=12, verbose_name='BHL Section')),
                ('shl_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='SHL Latitude (NAD83)')),
                ('shl_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='SHL Longitude (NAD83)')),
                ('first_perforation_depth', models.IntegerField(max_length=12, verbose_name='First Perforation Depth in ft')),
                ('last_perforation_depth', models.IntegerField(max_length=12, verbose_name='Last Perforation Depth in ft')),
                ('first_production', models.DateField(verbose_name='First Production')),
            ],
            options={
                'verbose_name': 'Well',
                'verbose_name_plural': 'Wells',
            },
        ),
    ]
