# Generated by Django 3.2.13 on 2022-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='bhl_section',
            field=models.IntegerField(verbose_name='BHL Section'),
        ),
        migrations.AlterField(
            model_name='well',
            name='cost_per_tonne',
            field=models.IntegerField(verbose_name='Cost Per Tonne in USD'),
        ),
        migrations.AlterField(
            model_name='well',
            name='first_perforation_depth',
            field=models.IntegerField(verbose_name='First Perforation Depth in ft'),
        ),
        migrations.AlterField(
            model_name='well',
            name='last_perforation_depth',
            field=models.IntegerField(verbose_name='Last Perforation Depth in ft'),
        ),
        migrations.AlterField(
            model_name='well',
            name='lease_id',
            field=models.IntegerField(verbose_name='Lease ID/Unit ID/Production ID'),
        ),
        migrations.AlterField(
            model_name='well',
            name='md',
            field=models.IntegerField(verbose_name='Measured Depth in ft'),
        ),
        migrations.AlterField(
            model_name='well',
            name='shl_section',
            field=models.IntegerField(verbose_name='SHL Section'),
        ),
        migrations.AlterField(
            model_name='well',
            name='tonnes',
            field=models.IntegerField(verbose_name='Tonnes Count'),
        ),
        migrations.AlterField(
            model_name='well',
            name='tvd',
            field=models.IntegerField(verbose_name='True Vertical Depth in ft'),
        ),
    ]
