# Generated by Django 3.2.13 on 2022-06-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_auto_20220629_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='blockchain',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Blockchain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='contract_address',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Contract Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='county',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='County'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='field',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='legal_description',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='legal_description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='metadata',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Metadata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='producing_formation',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Producing Formation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='range',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Range'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='state',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District Of Columbia', 'District Of Columbia'), ('Federated States Of Micronesia', 'Federated States Of Micronesia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Marshall Islands', 'Marshall Islands'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Palau', 'Palau'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], default='', max_length=64, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='token_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Token ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='township',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Township'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='well',
            name='well_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Well Type'),
            preserve_default=False,
        ),
    ]
