# Generated by Django 3.2.14 on 2022-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_auto_20220630_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='tonnes',
        ),
        migrations.AddField(
            model_name='well',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'Usa')], max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='well',
            name='tonnes_of_CO2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tonnes of CO2 Count'),
        ),
    ]
