# Generated by Django 3.2.14 on 2022-08-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_auto_20220803_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='source',
        ),
        migrations.RemoveField(
            model_name='well',
            name='type',
        ),
    ]
