# Generated by Django 3.2.14 on 2022-08-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_auto_20220803_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='tonnes_of_CO2',
            new_name='tonnes_of_cO2',
        ),
    ]
