# Generated by Django 3.2.14 on 2022-08-17 07:46

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0008_rename_tonnes_of_co2_well_tonnes_of_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='API ID'),
        ),
        migrations.AddField(
            model_name='well',
            name='current_operator',
            field=models.CharField(blank=True, max_length=64, verbose_name='Current Operator'),
        ),
        migrations.AddField(
            model_name='well',
            name='shl_latitude_nad27',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='SHL Latitude (NAD27)'),
        ),
        migrations.AddField(
            model_name='well',
            name='shl_longitude_nad27',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='SHL Longitude (NAD27)'),
        ),
        migrations.CreateModel(
            name='WellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='well-images/', verbose_name='Well Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Image Description')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_images', to='wells.well')),
            ],
        ),
    ]
