# Generated by Django 3.2.14 on 2022-08-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0010_remove_well_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellimage',
            options={'verbose_name': 'Well Image', 'verbose_name_plural': 'Well Images'},
        ),
    ]
