# Generated by Django 3.2.15 on 2022-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0011_alter_wellimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellimage',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=1023, verbose_name='ipfs hash'),
        ),
    ]
