# Generated by Django 3.2.15 on 2022-09-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0012_wellimage_ipfs_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='well-document/', verbose_name='Well Document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Document Description')),
                ('ipfs_hash', models.CharField(blank=True, max_length=1023, verbose_name='ipfs hash')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_documents', to='wells.well')),
            ],
            options={
                'verbose_name': 'Well Document',
                'verbose_name_plural': 'Well Documents',
            },
        ),
    ]
