# Generated by Django 3.2.15 on 2022-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0013_welldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='ipfs_metadata_url',
            field=models.CharField(blank=True, max_length=1023, verbose_name='IPFS Metadata URL'),
        ),
    ]
