# Generated by Django 3.2.15 on 2022-09-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0014_well_ipfs_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='api_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='API ID'),
        ),
    ]
