# Generated by Django 3.2.15 on 2022-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0016_auto_20220922_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiredtoken',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36, verbose_name='amount'),
        ),
    ]
