# Generated by Django 3.2.15 on 2022-10-04 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wells', '0017_alter_retiredtoken_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('retire', 'Retire'), ('purchase', 'Purchase')], default='retire', max_length=64, verbose_name='type')),
                ('transaction_hash', models.CharField(max_length=128, verbose_name='Transaction Hash')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36, verbose_name='amount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_token_transaction', to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_token_transaction', to='wells.well')),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
            },
        ),
        migrations.DeleteModel(
            name='RetiredToken',
        ),
    ]
