# Generated by Django 3.2.15 on 2022-09-14 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Location', 'Location')], max_length=64, verbose_name='Type')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('subscribers', models.ManyToManyField(null=True, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Type',
                'verbose_name_plural': 'Alert Types',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=128, verbose_name='Message')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_list', to='alerts.alerttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
