# Generated by Django 3.2.15 on 2022-09-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alerttype_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
