# Generated by Django 3.2.15 on 2022-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20220919_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='type',
            field=models.CharField(blank=True, choices=[('Location', 'Location')], max_length=128, verbose_name='Type'),
        ),
    ]
