# Generated by Django 3.2.15 on 2022-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20220919_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
