# Generated by Django 3.2.15 on 2022-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='isRead',
            new_name='is_read',
        ),
    ]
