# Generated by Django 3.2.15 on 2022-09-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_rename_isread_alert_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
    ]
