# Generated by Django 3.2.15 on 2022-09-19 05:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0011_alter_wellimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSAssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), blank=True, null=True, size=None, verbose_name='IPFS image hash')),
                ('file_hash', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), blank=True, null=True, size=None, verbose_name='IPFS file hash')),
                ('metadata_hash', models.CharField(blank=True, max_length=1024, verbose_name='IPFS metadata hash')),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipfs_asset_data', to='wells.well')),
            ],
            options={
                'verbose_name': 'IPFS Asset Data',
                'verbose_name_plural': 'IPFS Asset Data',
            },
        ),
    ]
